### ISSUE TITLE
pandoc: Error producing PDF from TeX source

### ISSUE THREAD

**Issue by vgprom** [akosma/PracticalCommonLisp_ePub#2]
Got the following error when executing "make pdf":

! Argument of \@sect has an extra }.
<inserted text> 
                \par 
l.517 ...def{}{why-lisp}{}{}Why Lisp?}{Why Lisp?}}

pandoc: Error producing PDF from TeX source
make: *** [create_pdf] Error 43

_______________________________
S.O. Mac OS 10.10.2
Pandoc: Pandoc 1.13.2
LaTeX: MacTeX 2014 (25 May 2014) full

**Comment by akosma** [comment]
Sorry, but that's an error generated by Pandoc, not by the makefile. Please file a bug report to Pandoc's creator instead.

**Comment by akosma** [comment]
Just in case, you can download a precompiled PDF from the "Releases" section of this repo.
